version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_API_URL=${NEXT_PUBLIC_SUPABASE_API_URL}
        - NEXT_PUBLIC_SUPABASE_API_KEY=${NEXT_PUBLIC_SUPABASE_API_KEY}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_SECRET=${AUTH_SECRET}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASS=${SMTP_PASS}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - AUTH_URL=${AUTH_URL}
        - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    image: bookings_v1-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run dev