name: Deploy Next.js Bookings App

on: 
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookings_v1-web:latest
          build-args: |
            NEXT_PUBLIC_SUPABASE_API_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_API_URL }}
            NEXT_PUBLIC_SUPABASE_API_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_API_KEY }}
            AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            SMTP_USER=${{ secrets.SMTP_USER }}
            SMTP_PASS=${{ secrets.SMTP_PASS }}
            SMTP_HOST=${{ secrets.SMTP_HOST }}
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            AUTH_URL=${{ secrets.AUTH_URL }}
            AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }}
